/*
 * File: app/view/AlbumsGrid.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.AlbumsGrid', {
    extend: 'sl.panel.grid.EditorGrid',
    alias: 'widget.albumsgrid',

    requires: [
        'Examples.view.AlbumsGridViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    config: {
        useStatusBar: false
    },

    viewModel: {
        type: 'albumsgrid'
    },
    reference: 'albums',
    title: 'Albums',
    columnLines: true,
    hideHeaders: true,
    includeSearch: false,
    includeRowCount: false,
    includeBufferedRenderer: false,
    includeFilters: false,
    includeStateViewPanel: false,
    useStewartsRenderer: true,
    includeRefreshBtn: false,
    includeExcelBtn: false,
    isLocalExcelExport: true,
    includeValidationStatus: false,
    singleName: 'Album',
    searchAlign: 'right',
    searchWidth: 200,
    selModelMode: 'MULTI',
    clicksToEdit: 2,
    useDefaultButtons: false,
    useDefaultSaveConfig: false,
    useDefaultDeleteConfig: false,
    useDefaultNewConfig: false,
    moveEditorOnEnter: true,
    useDefaultEnterKeyHandler: true,
    showEditCursor: true,

    bind: {
        store: '{albumsStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'title',
            text: 'Title'
        }
    ]

});