/*
 * File: app/view/FullSizePhoto.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.FullSizePhoto', {
    extend: 'Ext.Img',
    alias: 'widget.fullsizephoto',

    requires: [
        'Examples.view.FullSizePhotoViewModel',
        'Examples.view.FullSizePhotoViewController'
    ],

    config: {
        autoEl: 'div'
    },

    controller: 'fullsizephoto',
    viewModel: {
        type: 'fullsizephoto'
    },
    height: 600,
    width: 600,
    imgCls: 'centered-image',
    title: 'Full-Size Image',

    bind: {
        src: '{photo.url}'
    },
    listeners: {
        afterrender: 'onImageAfterRender'
    },

    setSrc: function(newSrc) {
        var img = this;

        img.setLoading('Loading...');

        return this.callParent(arguments);
    }

});