/*
 * File: app/view/PhotosGrid.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.PhotosGrid', {
    extend: 'sl.panel.grid.EditorGrid',
    alias: 'widget.photosgrid',

    requires: [
        'Examples.view.PhotosGridViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'photosgrid'
    },
    reference: 'photos',
    title: 'Photos',
    columnLines: true,
    includeSearch: true,
    includeRowCount: true,
    useStewartsRenderer: true,
    includeRefreshBtn: true,
    includeExcelBtn: true,
    isLocalExcelExport: true,
    includeValidationStatus: true,
    singleName: 'Photo',
    searchAlign: 'right',
    searchWidth: 200,
    selModelMode: 'MULTI',
    clicksToEdit: 2,
    useDefaultButtons: true,
    useDefaultSaveConfig: false,
    useDefaultDeleteConfig: false,
    useDefaultNewConfig: true,
    moveEditorOnEnter: true,
    useDefaultEnterKeyHandler: true,
    showEditCursor: true,

    bind: {
        store: '{photosStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'title',
            text: 'Title'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'url',
            text: 'Url'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'thumbnailUrl',
            text: 'Thumbnail Url'
        }
    ]

});