/*
 * File: app/view/PhotosView.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.PhotosView', {
    extend: 'Ext.view.View',
    alias: 'widget.photosview',

    requires: [
        'Examples.view.PhotosViewViewModel',
        'Examples.view.PhotosViewViewController',
        'Ext.XTemplate'
    ],

    config: {
        defaultTitle: null,
        title: null
    },

    controller: 'photosview',
    viewModel: {
        type: 'photosview'
    },
    reference: 'photos',
    scrollable: true,
    tpl: [
        '<tpl for=".">',
        '    <div class="thumb-wrap">',
        '        <div class="thumb">',
        '            <img src="{thumbnailUrl}" />',
        '        </div>',
        '        <span>{title}</span>',
        '    </div>',
        '</tpl>'
    ],
    itemSelector: 'div.thumb-wrap',
    overItemCls: 'x-view-over',
    trackOver: true,

    bind: {
        store: '{photosStore}'
    },
    listeners: {
        afterrender: 'addTooltipForEachPhoto',
        resize: 'onPhotosViewResize'
    }

});