/*
 * File: app/view/PhotosViewViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.PhotosViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.photosview',

    addPhotoTooltip: function(component, eOpts) {
        component.tip = Ext.create('Ext.tip.ToolTip', {
            target: component.getEl(),
            delegate: component.getItemSelector(),
            trackMouse: true,
            html: "Click to view photo's details"
        });
    }

});
