/*
 * File: app/view/UsersGridViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.UsersGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.usersgrid',

    onGridpanelBeforeRecordcreated: function(grid, defaultProperties) {
        defaultProperties.address = {
            "street": undefined,
            "suite": undefined,
            "city": undefined,
            "zipcode": undefined
        };

        defaultProperties.company = {
            "name": undefined,
            "catchPhrase": undefined,
            "bs": undefined
        };
    }

});
