/*
 * File: app/view/FullSizePhoto/SelectedImage.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.FullSizePhoto.SelectedImage', {
    extend: 'Ext.Img',
    alias: 'widget.fullsizephoto.selectedimage',

    requires: [
        'Examples.view.FullSizePhoto.SelectedImageViewModel',
        'Examples.view.FullSizePhoto.SelectedImageViewController'
    ],

    controller: 'fullsizephoto.selectedimage',
    viewModel: {
        type: 'fullsizephoto.selectedimage'
    },
    maxHeight: 600,
    maxWidth: 600,
    title: 'Full-Size Image',

    bind: {
        src: '{photo.url}'
    },
    listeners: {
        afterrender: 'onImageAfterRender'
    },

    setSrc: function(newSrc) {
        var img = this;

        img.setLoading('Loading...');

        return this.callParent(arguments);
    }

});