/*
 * File: app/view/FullSizePhoto/SelectedInformation.js
 *
 * This file was generated by Sencha Architect version 4.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.FullSizePhoto.SelectedInformation', {
    extend: 'Ext.container.Container',
    alias: 'widget.selectedinformation',

    requires: [
        'Examples.view.FullSizePhoto.SelectedInformationViewModel',
        'Examples.view.FullSizePhoto.SelectedPhoto',
        'Ext.Img',
        'Ext.form.FieldContainer',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'fullsizephoto.selectedinformation'
    },
    cls: 'full-size-photo',
    scrollable: 'y',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'selectedphoto'
        },
        {
            xtype: 'fieldcontainer',
            cls: 'details',
            scrollable: 'x',
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Title',
                    bind: {
                        value: '{photo.title}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'URL',
                    bind: {
                        value: '<a href="{photo.url}" target="_blank">{photo.url}</a>'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Thumbnail URL',
                    bind: {
                        value: '<a href="{photo.thumbnailUrl}" target="_blank">{photo.thumbnailUrl}</a>'
                    }
                }
            ]
        }
    ]

});