/*
 * File: app/view/FullSizePhoto/SelectedPanel.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Examples.view.FullSizePhoto.SelectedPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.selectedpanel',

    requires: [
        'Examples.view.FullSizePhoto.SelectedPanelViewModel',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'fullsizephoto.selectedpanel'
    },
    maxWidth: 612,
    width: 612,
    layout: 'fit',

    bind: {
        title: '{photo.title}'
    },
    tools: [
        {
            xtype: 'tool',
            type: 'toggle'
        }
    ]

});